defmodule PhoenixDiagrams.Components.Icons do
  @moduledoc false

  # Path markup vendored from heroicons v2.2.0 (https://heroicons.com), MIT
  # License, Copyright (c) 2020 Refactoring UI Inc. Only the specific icons
  # this library uses are kept, one per file under icons/, to avoid
  # depending on a Hex/git package whose name (`:heroicons`) commonly
  # collides with host apps generated by `mix phx.new`, which vendor their
  # own `:heroicons` dependency. `sidebar_collapse` and `logo` are custom
  # icons, not from heroicons, but share the same outline svg wrapper shape.

  use Phoenix.Component

  @icons_dir Path.join(__DIR__, "../icons")

  @outline ~w(bars_3 sun moon arrow_down_tray magnifying_glass magnifying_glass_minus magnifying_glass_plus
               arrow_path arrows_pointing_out arrows_pointing_in document_duplicate
               sidebar_collapse logo x_mark)a
  @solid ~w(share)a

  Module.register_attribute(__MODULE__, :paths, accumulate: true)

  for name <- @outline ++ @solid do
    file = Path.join(@icons_dir, "#{name}.svg")
    @external_resource file
    [_, inner] = Regex.run(~r/<svg[^>]*>(.*)<\/svg>/s, File.read!(file))
    Module.put_attribute(__MODULE__, :paths, {name, String.trim(inner)})
  end

  for {name, path} <- Module.get_attribute(__MODULE__, :paths), name in @outline do
    attr(:class, :string, default: nil)
    attr(:rest, :global)

    def unquote(name)(assigns) do
      assigns = assign(assigns, :path, unquote(path))

      ~H"""
      <svg xmlns="http://www.w3.org/2000/svg" class={@class} fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" {@rest}>
        {Phoenix.HTML.raw(@path)}
      </svg>
      """
    end
  end

  for {name, path} <- Module.get_attribute(__MODULE__, :paths), name in @solid do
    attr(:class, :string, default: nil)
    attr(:rest, :global)

    def unquote(name)(assigns) do
      assigns = assign(assigns, :path, unquote(path))

      ~H"""
      <svg xmlns="http://www.w3.org/2000/svg" class={@class} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {@rest}>
        {Phoenix.HTML.raw(@path)}
      </svg>
      """
    end
  end
end
